[package]
name = "bloom_bench"
version = "0.1.0"
edition = "2024"

[features]
default = []
use_unsafe = ["lsm-tree/bloom_use_unsafe"]

[dependencies]
lsm-tree = { path = "../..", features = ["lz4"] }
rand = "0.9.0"
