[package]
name = "fractional_bench"
version = "0.1.0"
edition = "2024"

[features]
default = ["fast_partition_point"]
cascading = []
fast_partition_point = []
use_unsafe = ["lsm-tree/use_unsafe"]

[dependencies]
lsm-tree = { path = "../.." }
rand = "0.9.1"
